name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Установить зависимости frontend
        run: |
          cd frontend
          npm install

      - name: Проверка сборки frontend
        run: |
          cd frontend
          npm run build
